config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  resources :people
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord



    def full_name
        "#{self.first_name} #{self.last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(people_params)

    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update(people_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end


  private
  def people_params
    params.require(:person).permit(:first_name, :last_name, :age, :gender, :hair_color, :eye_color, :alive)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1> Edit <%= @person.first_name%>'s Info</h1>
<%= form_for @person do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br>
    <%= f.label :age %>
    <%= f.number_field :age %>
    <br>
    <%= f.label :gender %>
    <%= f.text_field :gender %>
    <br>
    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>
    <br>
    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>
    <br>
    <%= f.label :alive %>
    <%= f.text_field :alive %>
    <br>

    <%= f.submit %>
    <% end %>

app/views/people/index.html.erb
<h1>My Contacts</h1>
<p><%= link_to "Create New Contact", new_person_path %></p>
<% @people.each do |person| %>
    <h2><%= person.full_name %></h2>
    <%= link_to 'Show', person_path(person) %>
    <%= link_to 'Edit', edit_person_path(person) %>
    <%= link_to 'Delete', person, method: :delete %>
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for @person do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br>
    <%= f.label :age %>
    <%= f.number_field :age %>
    <br>
    <%= f.label :gender %>
    <%= f.text_field :gender %>
    <br>
    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>
    <br>
    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>
    <br>
    <%= f.label :alive %>
    <%= f.text_field :alive %>
    <br>

    <%= f.submit %>
    <% end %>

app/views/people/show.html.erb
<h1><%= @person.full_name %></h1>
<p>Age: &nbsp; <strong><%= @person.age %></strong></p>
<p>Gender: &nbsp;<strong><%= @person.gender %></strong></p>
<p>Hair Color: &nbsp;<strong><%= @person.hair_color %></strong></p>
<p>Eye Color: &nbsp;<strong><%= @person.eye_color %></strong></p>
<p>Alive: &nbsp;<strong><%= @person.alive %></strong></p>
<%= link_to "Back", people_path %>